modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Christofmeg/IC2C-UU-Matter/issues" #optional
license="MIT License https://github.com/Christofmeg/IC2C-UU-Matter/blob/1.19.2/LICENSE"
[[mods]]
modId="ic2cuumatter"
version="1.19.2-1.2.0"
displayName="IC2C UU-Matter"
displayURL="https://github.com/Christofmeg/IC2C-UU-Matter" #optional
logoFile="pack.png"
#credits=""
authors="Christofmeg"
description='''
Addon for IC2-Classic adding JEI pages for UU-Matter and Plasma Cell creation.
'''
[[dependencies.ic2cuumatter]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ic2cuumatter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ic2cuumatter]]
    modId="ic2"
    mandatory=true
    versionRange="[1.19.2-2.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.ic2cuumatter]]
    modId="jei"
    mandatory=true
    versionRange="[11.4.0.287,)"
    ordering="NONE"
    side="BOTH"
